### ISSUE TITLE
Moving with gamepad joystick replaces custom text with default text.

### ISSUE THREAD

**Issue by c0ffee-cup** [Repooc/ElvUI_KeybindDisplay#1]
I'm currently having an issue where my custom keybind text is replaced by the "normal" keybind text when I use a gamepad joystick to move. I'm able to restore the custom text by toggling the `Use ElvUI Short Keybind Text` option off and on, at which point it remains in place as long as I move using my keyboard. As soon as I use my joystick to move, the text goes back to its default value.

If use-case details are helpful, I'm using an Azeron Cyborg II with its joystick configured to act as an Xbox 360 joystick and all other buttons mapped to regular keyboard buttons. WoW handles this very well with gamepad mode enabled (`/console GamePadEnable 1`). The only hangup is the issue I'm reporting as it prevents me from using custom keybind text.

My game and add-on versions are listed below:
* WoW Client: 11.0.2.56819
* ElvUI: 13.78
* ElvUI_KeybindDisplay: 1.11

**Comment by c0ffee-cup** [comment]
After some tinkering, I was able to narrow down the source of this behavior: the `GAME_PAD_ACTIVE_CHANGED` event. Using `/etrace` I was able to confirm that this event fired every time I moved the joystick. This appears to trigger [an event handler in LibActionButton-1.0 that forces a hotkey update](https://github.com/tukui-org/ElvUI/blob/main/ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua#L1562-L1563). I was able to "fix" this issue by modifying line 1562 to read:

```lua
elseif event == "UPDATE_BINDINGS" then
```

With the above change, the custom keybind text set using this add-on persists when using the joystick to move.

Since this appears to be related to one of the main ElvUI libraries and not this add-on, would it be more appropriate to file an issue describing this finding in the main ElvUI repo?

_Edited to point to main branch of ElvUI repo._

**Comment by Repooc** [comment]
You on my discord by chance? If not, can you tell me when the custom text reverts to not using the custom text? I have figured a workaround on reloadui.

**Comment by Repooc** [comment]
try the alpha version which u can use a client like wowup to obtain it by changing to alpha release

**Comment by Repooc** [comment]
let me know if this fixes the issue and such so i can do an update, reopen if u have the issue with how to reproduce the issue

**Comment by c0ffee-cup** [comment]
That did the trick! 😄 I reverted the change I made to LibActionButton-1.0, applied your fix, and now the custom keybind text remains as it should when swapping between my Cyborg II and keyboard.
